### ISSUE TITLE
`OrderShippingExtension::setShippingMethod` calls unavailable `error` method.

### ISSUE THREAD

**Issue by bummzack** [silvershop/silvershop-shipping#21]
Resulting in:

```
Fatal error: Call to undefined method OrderShippingExtension::error()
```

This occurs when there's no shipping address set, or `createShippingPackage` returns `null`.

I'm not sure how errors are triggered in other extensions, but maybe throw an exception instead?

**Comment by markguinn** [comment]
My guess is that should be $this->owner->error() but I don't know for sure. I haven't used this module yet in production.

**Comment by bummzack** [comment]
I've tried that but I also get an error

    Uncaught Exception: Object->__call(): the method 'error' does not exist on 'Order'

**Comment by markguinn** [comment]
I would be inclined to throw an exception there. @jedateach can you speak to the original intention at all?

**Comment by ctx2002** [comment]
I have this problem, OrderShippingExtension is an Order Extension, and there is no error() method in Order model.

**Comment by jameshoward** [comment]
I am having the same issue. I wonder if the intention was to call `ShoppingCart::error` or `Checkout:error`, both of which exist. There's also an `error` method on `OrderProcessor`.

**Comment by asecondwill** [comment]
Same error here.  is there a workaround?  I only get the error when the user is signed out.

**Comment by asecondwill** [comment]
oh, because no address set.  so it has to be later in the steps.

**Comment by wilr** [comment]
Fix merged, closing.
