### ISSUE TITLE
setShippingMethod should not rely on an address being present.

### ISSUE THREAD

**Issue by bummzack** [silvershop/silvershop-shipping#22]
Consider the following use-case:
- Shop ships to one country only
- Shipping cost is only calculated by quantity or total order-value

In the above case, the shipping modifier could be applied to an order before a user-address is present. It could even show the actual shipping cost inside the cart, at a time where the user-address might be unknown.

My proposal would be to implement a `requiresAddress` method for each `ShippingMethod` implementation. ZonedShipping and DistanceShipping would obivously simply return `true`, but TableShipping could return either true or false.

Should I try to implement this change?

**Comment by markguinn** [comment]
I think this makes sense.

**Comment by jameshoward** [comment]
Having the same issue with shipping on our site. The shipping cost is based on number of items rather than where they are being shipped to. There's also a free collection option that shouldn't require an address at all.

The suggested change sounds great.
