### ISSUE TITLE
Requiring Silverstripe Shop

### ISSUE THREAD

**Issue by jameslongstaff** [silvershop/silvershop-shipping#26]
Hi there,

I am trying to require the updated version of the shipping module.

composer require silvershop/silvershop-shipping:master

I am having trouble requiring the module. Getting the following error when I run the command:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package silvershop/silvershop-shipping could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I can require via 'composer require silvershop/shipping'. However the version this installs is not up to date.

Best regards,
James

**Comment by markguinn** [comment]
I think you want `silvershop/shipping` for the composer package name.

**Comment by jameslongstaff** [comment]
Ah right. I've added silvershop/shipping:master to the require statement and this has worked. Do the packagist and github instructions need to be updated to use : silvershop/shipping master rather than silvershop/silvershop-shipping:master, that causes error when requiring?

**Comment by markguinn** [comment]
Looks like there was a typo there in the README. Sorry about that!

**Comment by jameslongstaff** [comment]
No problem, cheers for your help.
