### ISSUE TITLE
Shipping address issue

### ISSUE THREAD

**Issue by ctx2002** [silvershop/silvershop-shipping#27]
I have an ajax call, the call uses following code to get $shipping object:

**$method = ShippingMethod::get()->filter(array("ID" => $id))->first();
$order = ShoppingCart::curr();
$shipping = $method->getCalculator($order)->calculate();**

above was working with old burnbright/shop module, since the old module was no longer supported, 
I have changed to use silvershop/core.

Now there is a problem,

for ShippingCalculator class, to get address, it uses following line:

$this->order->ShippingAddress()

I think it should change to getShippingAddress.
In older version of Order class, ShippingAddress is correct way to fetch address,

**Comment by wilr** [comment]
Hi @ctx2002 Can you submit a PR with the working change? Thanks
