### ISSUE TITLE
Shipping shows as $0 until shipping method is chosen

### ISSUE THREAD

**Issue by asecondwill** [silvershop/silvershop-shipping#38]
Looks odd /  miss-leading the user.  
![screen shot 2017-05-09 at 21 17 33](https://cloud.githubusercontent.com/assets/156546/25870712/fb39b596-34fc-11e7-9d02-c011aad28996.png)

**Comment by mhenden** [comment]
I have the same problem! All I need to do is add a pre-set shipping fee for either of two zones (New Zealand and Australia).

**Comment by wilr** [comment]
Closing this as a duplicate of #39
