### ISSUE TITLE
Disabling shipping on Virtual or digital products

### ISSUE THREAD

**Issue by andrewamon** [silvershop/silvershop-shipping#41]
I was wondering if there is away to disable shipping on digital or virtual products

**Comment by wilr** [comment]
Yes! But if your store has both digital and non digital best method I can think of is you can use a `TableShippingMethod` based on weight or volume with a default rate of $0 for a total weight of < 1 and your normal shipping rate applies at > 1. Once you apply weights to all your products (and no weight to the digital ones, it'll work).
