### ISSUE TITLE
Fatal error When adding Warehouse

### ISSUE THREAD

**Issue by nzrubin** [silvershop/silvershop-shipping#46]
hello
could you advise please!
im getting an error when trying to add a Warehouse

Fatal error: Class 'SilverStripe\Forms\GridField\GridField' not found in C:\wamp\www\myshop\hasonefield\code\HasOneButtonField.php on line 13

i have now SilverStripe 3.6
below is my info of what i got

"require": {
		"php": ">=5.3.3",
		"silverstripe/cms": "^3.1",
		"silverstripe/framework": "^3.1",
		"silverstripe/reports": "^3.1",
		"silverstripe/siteconfig": "^3.1",
		"silvershop/core": "^2.2",
		"burnbright/omnipay-paystation": "~2.0",
		"omnipay/paymentexpress": "~2.0",
		"unclecheese/betterbuttons": "1.2.*",
		"silverstripe/googlesitemaps": "^1.5",
		"silverstripe/userforms": "*",
		"silverstripe/blog": "2.*@dev",
		"silverstripe/comments": "^2.1",
		"ezyang/htmlpurifier": "dev-master",
		"thisisbd/silverstripe-maintenance-mode": "*",
		"heyday/silverstripe-menumanager": "~2.1.0",
		"silvershop/shipping": "master"
	},

**Comment by nzrubin** [comment]
not sure what happened but after i added a Stock module all became just fine .... 
i hope it will help somebody or give some hint

**Comment by wilr** [comment]
`SilverStripe\Forms\GridField\GridField` is a SilverStripe 4.0 namespace not 3.6 which would indicate that perhaps you updated to 4.0?
