### ISSUE TITLE
This module should not rely on constants defined in the core module.

### ISSUE THREAD

**Issue by bummzack** [silvershop/silvershop-shipping#47]
There are some constants being defined in `_config.php` that rely on constants from the core module. We should remove those, because it relies on the fact that the `_config.php` file from the core module gets loaded first. Not sure where/why these constants are being used anyway.

**Comment by wilr** [comment]
Just `SHOP_DIR` right? This is redundant anyway in `4.0` but probably not worth changing until the module upgrade.

**Comment by wilr** [comment]
Removed in latest build
