### ISSUE TITLE
Bug introduced in #61

### ISSUE THREAD

**Issue by wernerkrauss** [silvershop/silvershop-shipping#62]
in #61 @RVXD changed the value taken for calculating shipping costs to order's "Total" instead of SubTotal.

This introduces a bug when using TableShippingRates and stepped checkout.

Imagine a SubTotal of 75,-
Under 80,- we have a shipping fee of 10,-
Now the Total is 85,- and saved to the order object.

In the next step it calculates the shipping fee again, but now it uses the saved Total of 85,- to calculate it. Unfortunately this is just above free shipping limit.

The user sees a total calculated ammount of 75,- (Subtotal and no shipping), but internally the order is still worth 85,- .

Now the problems are really starting: The customer is sent to the payment gateway to pay the last calculated amount of 75,-, the order is not fully paid.

IMHO we should revert #61 and the discounts module should modify the value of "createShippingPackage" using the provided hook "updateShippingPackage"

**Comment by wilr** [comment]
@wernerkrauss I see what you mean, 61 has been reverted for now

**Comment by RVXD** [comment]
@wernerkrauss Maybe you can test this fix, it should work good for both our cases.
